import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/** Autogenerated from `docs/` — Backend pages live under `docs/apps/be/` (overview, testing). */
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
