export const ENV_KEYS = {
  MONGODB_URI: 'MONGODB_URI',
  MONGODB_DATABASE: 'MONGODB_DATABASE',
  E2E_MONGODB_URI: 'E2E_MONGODB_URI',
  NODE_ENV: 'NODE_ENV',
  VITE_NODE_ENV: 'VITE_NODE_ENV',
  VITE_REDUX_PERSIST_SECRET_KEY: 'VITE_REDUX_PERSIST_SECRET_KEY',
};
