export const ENV_KEYS = {
  MONGODB_URI: 'MONGODB_URI',
  MONGODB_DATABASE: 'MONGODB_DATABASE',
  E2E_MONGODB_URI: 'E2E_MONGODB_URI',
  FRONTEND_ORIGIN: 'FRONTEND_ORIGIN',
  AUTH_ACCESS_TOKEN_SECRET: 'AUTH_ACCESS_TOKEN_SECRET',
  AUTH_REFRESH_TOKEN_SECRET: 'AUTH_REFRESH_TOKEN_SECRET',
  AUTH_ACCESS_TOKEN_TTL_SECONDS: 'AUTH_ACCESS_TOKEN_TTL_SECONDS',
  AUTH_REFRESH_TOKEN_TTL_SECONDS: 'AUTH_REFRESH_TOKEN_TTL_SECONDS',
  AUTH_ACCESS_COOKIE_NAME: 'AUTH_ACCESS_COOKIE_NAME',
  AUTH_REFRESH_COOKIE_NAME: 'AUTH_REFRESH_COOKIE_NAME',
  AUTH_COOKIE_SAME_SITE: 'AUTH_COOKIE_SAME_SITE',
  AUTH_CSRF_SECRET: 'AUTH_CSRF_SECRET',
  AUTH_CSRF_COOKIE_NAME: 'AUTH_CSRF_COOKIE_NAME',
  VITE_CSRF_COOKIE_NAME: 'VITE_CSRF_COOKIE_NAME',
  NODE_ENV: 'NODE_ENV',
  VITE_NODE_ENV: 'VITE_NODE_ENV',
  VITE_API_URL: 'VITE_API_URL',
  VITE_ALLOWED_HOSTS: 'VITE_ALLOWED_HOSTS',
  VITE_HOST: 'VITE_HOST',
  VITE_REDUX_PERSIST_SECRET_KEY: 'VITE_REDUX_PERSIST_SECRET_KEY',
  /** Comma-separated origins allowed by BE CORS (must include the FE dev URL). */
  CORS_ORIGIN: 'CORS_ORIGIN',
  /** Auth route rate limit window in milliseconds (per IP). */
  AUTH_THROTTLE_TTL_MS: 'AUTH_THROTTLE_TTL_MS',
  /** Max auth requests per IP within AUTH_THROTTLE_TTL_MS. */
  AUTH_THROTTLE_LIMIT: 'AUTH_THROTTLE_LIMIT',
  /** Express JSON / urlencoded body size limit (e.g. `100kb`, `1mb`). */
  BE_JSON_BODY_LIMIT: 'BE_JSON_BODY_LIMIT',
};
